name: docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip setuptools
      - run: pip install --no-cache-dir mkdocs-material mkdocs-jupyter
      - run: pip freeze | grep mkdocs  # Debug: List installed mkdocs plugins
      - run: python -c "from mkdocs.plugins import get_plugins; print(get_plugins())"
      - run: mkdocs gh-deploy --force